### ISSUE TITLE
The split at obsidian-repos-downloader.py line 135 dies for "threethan/obsidian-material-flat-theme/"

### ISSUE THREAD

**Issue by wagle** [claremacrae/obsidian-repos-downloader#20]
The split at obsidian-repos-downloader.py line 135 dies for "threethan/obsidian-material-flat-theme/"

(I inserted a print(repo) at line 135)

  File "/Users/wagle/Documents/Obsidian/obsidian-plugin-repos/../obsidian-repos-downloader/obsidian-repos-downloader.py", line 136, in clone_or_update_repo
    user, repo_name = repo.split("/")
ValueError: too many values to unpack (expected 2)

**Comment by claremacrae** [comment]
Many thanks for reporting this.

I've put in a request to fix the formatting in the community list of themes:

- https://github.com/obsidianmd/obsidian-releases/pull/1934

If you subscribe to that ticket, you will get a notification when it is merged, and then you can try my downloader script again.

**Comment by claremacrae** [comment]
That fix in the community list of themes has been merged already, so this script should work fine now.
Thanks again.
